version: '3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restuser

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql:3306/restuser -schemas=restuser -user=root -password=root -connectRetries=03 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql

  restapi:
    image: restapi:1.1
    ports:
      - "8080:8080"
    environment:
      - spring.datasource=mysql
      - spring.datasource.url=jdbc:mysql://mysql:3306/restuser?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.hikari.schema=restuser
#      - spring.datasource.driver-class-name=org.mysql.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.mail.username=vktrenga@gmail.com
      - spring.mail.password=25041987
      - spring.mail.properties.mail.smtp.auth=true
      - jwt.secret=123456
    depends_on:
      - mysql
      - flyway